from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).parents[1]

ROUTE_REJECTION_PHRASES: tuple[str, ...] = (
    "editable third-party entry surface",
    "framework-specific plugin marketplaces, IDE agent extension marketplaces",
    "single-app tool collections, offline marketplace mirrors",
    "Dify, LangGraph, LlamaIndex, AutoGen, OpenAI Agents SDK",
    "Cline, Roo Code, Cursor, Windsurf",
    "Open WebUI, LibreChat, AnythingLLM, BeeAI, Rivet",
    "Langroid, AutoGPT Forge, OpenAgents, Agent Zero, SuperAGI, BabyAGI",
    "Smolagents, DSPy, Julep, MetaGPT, Qwen-Agent, PraisonAI, Swarms",
    "Letta, MemGPT, Griptape, Mirascope, Marvin AI, Agency Swarm, Phidata, Motia",
    "Flowise, Haystack, Sema4.ai, MindsDB",
    "Hermes Tweet's shipped package format",
    "tool subclass, module, framework tool",
    "extension, action, pipeline",
    "agent-framework runtime toolkits",
    "AutoGen, CrewAI, LangGraph",
    "Mastra, Letta, and Semantic Kernel",
    "runtime-specific tool implementation",
    "adapter class, graph node, agent action",
    "plugin function instead of a source-linked",
    "hosted agent builder, assistant builder, toolgroup, and action-group",
    "Chainlit, Microsoft PromptFlow, Llama Stack, CopilotKit, Rasa",
    "CALM, or AWS Bedrock Agents",
    "app-native tools",
    "declarative action groups",
    "prompt-flow components",
    "runtime-specific tool definitions",
    "integration targets, not Hermes Tweet outreach routes",
    "licensed PR-editable catalog entry",
    "Hermes Tweet's shipped source repository package",
    "hosted AI app directories",
    "assistant action galleries",
    "ChatGPT apps, OpenAI Apps SDK examples",
    "GPT action directories, MCP UI registries",
    "Vercel AI SDK templates",
    "LangChain Hub snippets",
    "app manifests, UI widgets, action schemas",
    "SDK demos, or hub snippets",
    "prompt, evaluation, and observability hubs",
    "LangSmith Hub, PromptLayer, Langfuse",
    "Braintrust, promptfoo, or OpenPipe",
    "prompt templates, eval datasets",
    "trace dashboards, eval configs",
    "experiment recipes",
    "model hubs, dataset marketplaces",
    "annotation-template catalogs",
    "synthetic-data marketplaces",
    "MLOps registries",
    "Hugging Face Spaces",
    "Hugging Face model hubs",
    "Replicate collections",
    "Kaggle datasets",
    "Papers With Code",
    "Roboflow Universe",
    "Label Studio templates",
    "Scale AI marketplaces",
    "model registry catalogs",
    "hosted models, demo spaces",
    "notebooks, datasets",
    "benchmark links, annotation tasks",
    "labeling templates",
    "synthetic-data packages",
    "model deployment recipes",
    "RAG, retrieval, and vector-store integration catalogs",
    "LlamaHub",
    "Pinecone Assistant, Weaviate, Qdrant",
    "data loaders, vector indexes",
    "retriever classes, ingestion pipelines",
    "notebook, data-app, and BI assistant galleries",
    "Jupyter AI",
    "NotebookLM, marimo, Hex, Deepnote",
    "Observable Framework, or Databricks Apps",
    "notebooks, magic commands",
    "workspace recipes, or data-app examples",
    "data-visualization, dashboarding",
    "charting, and BI visual marketplaces",
    "Tableau Exchange",
    "Power BI visuals marketplace",
    "Looker Marketplace",
    "Metabase plugins",
    "Apache Superset extensions",
    "Observable visualization plugins",
    "Chart.js plugin registries",
    "D3 plugin catalogs",
    "dashboard widget marketplaces",
    "reporting widget marketplaces",
    "dashboard templates",
    "visual components, chart plugins",
    "BI connectors, metric widgets",
    "report blocks",
    "data exploration examples",
    "platform-native visualization packages",
    "browser-automation and computer-use agent toolkits",
    "Browser Use",
    "Stagehand, Browserbase, Hyperbrowser",
    "Playwright agent tools",
    "browser task scripts",
    "replay recipes, hosted browser workflows",
    "DOM automation examples",
    "computer-use action packs",
    "enterprise hosted-agent surfaces",
    "Google Vertex AI Agent Builder",
    "Salesforce Agentforce",
    "ServiceNow AI Agent Studio",
    "Oracle AI Agent Studio",
    "Slack agent platform tools",
    "Mistral agent connectors",
    "platform-native extensions",
    "managed-agent definitions",
    "productivity and workspace app directories",
    "Google Workspace",
    "Microsoft Teams apps, Slack App Directory",
    "Notion, Airtable",
    "monday.com, or Asana",
    "app add-ons, workspace bots",
    "slash-command apps, database blocks",
    "workspace automations, or product-specific integrations",
    "localization, translation-management",
    "i18n, and CAT-tool marketplaces",
    "Crowdin Marketplace",
    "Lokalise app marketplace",
    "Phrase integrations",
    "Transifex integrations",
    "Weblate add-ons",
    "Smartling marketplace",
    "DeepL app marketplace",
    "Google Translate integrations",
    "translation memory connectors",
    "glossary sync apps",
    "localization workflow automations",
    "machine-translation plugins",
    "string extraction tools",
    "project webhooks",
    "translation-provider extensions",
    "CRM, support, and commerce app marketplaces",
    "HubSpot Marketplace",
    "Salesforce AppExchange, Zendesk Marketplace",
    "Intercom App Store, Freshworks",
    "Pipedrive Marketplace, Zoho Marketplace",
    "Shopify App Store",
    "CRM apps, support widgets",
    "sales automations, helpdesk macros",
    "commerce app packages, or storefront integrations",
    "community chat and bot directories",
    "Discord App Directory",
    "Discord bot lists, Telegram bot catalogs",
    "Matrix bot directories, Mastodon app",
    "Reddit app directories, or Twitch Extension Marketplace",
    "chat bots, server apps",
    "slash commands, moderation workflows",
    "social feed relays, or extension packages",
    "CMS, content publishing, and creator platform marketplaces",
    "WordPress Plugin Directory",
    "Drupal module directory, Ghost integrations",
    "Webflow App Marketplace, Wix App Market",
    "Squarespace Extensions",
    "CMS plugins, theme extensions",
    "site widgets, publishing automations",
    "website-builder app packages",
    "social listening, brand monitoring",
    "marketing analytics app",
    "Hootsuite App Directory",
    "Buffer integrations, Sprout Social",
    "Semrush App Center",
    "brand-monitoring integration galleries",
    "dashboards, analytics connectors",
    "campaign automations, social inbox apps",
    "platform-specific integrations",
    "SEO, search-console, web analytics",
    "advertising partner marketplaces",
    "Google Search Console integrations",
    "Bing Webmaster Tools integrations",
    "Ahrefs app marketplace",
    "Moz app marketplace",
    "Similarweb integrations",
    "Google Analytics integrations",
    "Adobe Analytics Exchange",
    "Google Ads marketplace",
    "Meta Business Partner Marketplace",
    "adtech marketplaces",
    "site-verification integrations",
    "keyword rank trackers",
    "SEO audit dashboards",
    "tag-management connectors",
    "conversion tracking packages",
    "ads automation apps",
    "partner-program listings",
    "LMS, documentation, and knowledge-base marketplaces",
    "Moodle Plugin Directory",
    "Canvas LMS integrations, Blackboard",
    "Confluence Marketplace",
    "GitBook integrations",
    "knowledge-base app marketplaces",
    "course plugins, learning-tool integrations",
    "documentation widgets, space macros",
    "help-center automations",
    "knowledge-base connectors",
    "API marketplaces, public API networks",
    "developer portal catalogs",
    "RapidAPI",
    "Postman Public API Network",
    "SwaggerHub, Stoplight, ReadMe",
    "Kong Plugin Hub",
    "API gateway marketplaces",
    "API specs, hosted API listings",
    "request collections, docs workspaces",
    "gateway plugins",
    "API management connectors",
    "data warehouse, ETL, reverse ETL",
    "customer data platform",
    "Snowflake Marketplace",
    "dbt Package Hub",
    "Airbyte connectors",
    "Fivetran connectors",
    "Hightouch destinations",
    "Census integrations",
    "Segment integrations",
    "data integration catalogs",
    "data connectors",
    "warehouse apps",
    "transform packages",
    "destination syncs",
    "ingestion pipelines",
    "customer profile activations",
    "platform-native data app packages",
    "finance, accounting, payroll",
    "procurement, and ERP app marketplaces",
    "QuickBooks App Store",
    "Xero App Store",
    "NetSuite SuiteApps",
    "SAP Store",
    "Workday Marketplace",
    "ADP Marketplace",
    "Stripe App Marketplace",
    "procurement app marketplaces",
    "accounting connectors, billing apps",
    "payroll automations",
    "procurement workflows, ERP extensions",
    "platform-native financial integration packages",
    "Web3, crypto wallet, dapp",
    "NFT, and decentralized social marketplaces",
    "MetaMask Snaps",
    "WalletConnect AppKit plugins",
    "Alchemy dapp galleries",
    "thirdweb marketplaces",
    "Chainlink Functions galleries",
    "OpenSea app marketplaces",
    "Farcaster frame catalogs",
    "Lens Protocol app directories",
    "wallet plugin marketplaces",
    "wallet extensions, dapp templates",
    "smart-contract functions",
    "NFT storefront apps",
    "blockchain connectors",
    "decentralized social frames",
    "token-gated app packages",
    "HR, recruiting, talent",
    "benefits, and workforce app marketplaces",
    "Greenhouse integrations",
    "Lever integrations",
    "Ashby marketplace",
    "Workable app marketplace",
    "BambooHR app marketplace",
    "Gusto integrations",
    "LinkedIn Talent Solutions partner apps",
    "recruiting app marketplaces",
    "ATS connectors",
    "candidate-source automations",
    "job board integrations",
    "interview workflows",
    "employee-directory apps",
    "benefits connectors",
    "onboarding tasks",
    "workforce platform packages",
    "healthcare, EHR, FHIR",
    "telehealth, wellness, and fitness app",
    "Epic App Orchard",
    "Oracle Health App Gallery",
    "SMART App Gallery",
    "FHIR app galleries",
    "athenahealth Marketplace",
    "telehealth app marketplaces",
    "wellness app marketplaces",
    "fitness app marketplaces",
    "EHR integrations, clinical apps",
    "FHIR launch apps",
    "patient portal widgets",
    "care workflows, wellness programs",
    "device integrations",
    "platform-native health app packages",
    "legal, compliance, e-signature",
    "identity, KYC, contract automation",
    "eDiscovery, GRC, and privacy automation app marketplaces",
    "Clio App Directory",
    "DocuSign App Center",
    "Adobe Acrobat Sign integrations",
    "Okta Integration Network",
    "Auth0 Marketplace",
    "OneTrust app catalogs",
    "Vanta integrations",
    "Drata integrations",
    "Relativity app directories",
    "contract lifecycle marketplaces",
    "compliance automation marketplaces",
    "legaltech connectors",
    "e-signature connectors",
    "identity integrations",
    "compliance controls",
    "audit workflows",
    "eDiscovery workflows",
    "contract templates",
    "trust-center automations",
    "KYC checks",
    "privacy assessments",
    "platform-native governance apps",
    "security operations, SIEM, SOAR",
    "observability integration catalogs",
    "Splunkbase, Elastic integrations",
    "Datadog integrations",
    "Grafana plugin catalog",
    "New Relic Instant Observability",
    "Sumo Logic app catalog",
    "Cortex XSOAR content packs",
    "dashboards, detection rules",
    "log parsers, alert connectors",
    "runbooks, incident workflows",
    "platform-specific integration packages",
    "CI/CD, DevOps automation",
    "pipeline extension marketplaces",
    "GitHub Marketplace Actions",
    "GitLab CI/CD Catalog",
    "CircleCI orb registry",
    "Jenkins plugin index",
    "Buildkite plugins",
    "Travis CI add-ons",
    "pipeline automation marketplaces",
    "workflow actions, CI templates",
    "orb packages, build plugins",
    "deployment automations",
    "source-control workflows",
    "container, cloud-native",
    "infrastructure packaging registries",
    "Docker Hub extensions",
    "Kubernetes operator catalogs",
    "Helm chart repositories",
    "Artifact Hub",
    "Terraform Registry, Pulumi Registry",
    "Crossplane package registry",
    "Backstage plugin catalogs",
    "container images, operators",
    "charts, infrastructure providers",
    "platform plugins, or deployment packages",
    "IoT, smart-home, industrial-device",
    "maker hardware marketplaces",
    "Home Assistant integrations",
    "HACS repositories",
    "SmartThings Edge drivers",
    "Hubitat apps",
    "Matter plugin catalogs",
    "Node-RED flow libraries",
    "Arduino Library Manager",
    "Raspberry Pi project galleries",
    "industrial IoT app marketplaces",
    "device plugin catalogs",
    "home automation integrations",
    "device drivers, flow recipes",
    "firmware libraries",
    "hardware projects, sensor connectors",
    "platform-native device packages",
    "CAD, CAM, PLM, EDA",
    "additive manufacturing app marketplaces",
    "Autodesk App Store",
    "Fusion 360 add-ins",
    "SolidWorks marketplace",
    "Onshape App Store",
    "Altium extensions",
    "KiCad plugin repositories",
    "FreeCAD Addon Manager",
    "CAD plugin marketplaces",
    "PLM app stores",
    "EDA plugin catalogs",
    "manufacturing app marketplaces",
    "engineering add-ins",
    "CAD toolbars, model plugins",
    "circuit-design extensions",
    "CAM post-processors",
    "slicer integrations",
    "simulation templates",
    "manufacturing workflows",
    "platform-native engineering packages",
    "browser, desktop, launcher",
    "shortcut, and mobile app extension stores",
    "Chrome Web Store",
    "Firefox Add-ons",
    "Microsoft Edge Add-ons",
    "Raycast extensions",
    "Alfred workflows",
    "iOS Shortcuts galleries",
    "Android app marketplaces",
    "browser extensions, desktop launcher",
    "mobile intents, automation shortcuts",
    "app-store listings",
    "design, creative, whiteboard",
    "knowledge-app plugin marketplaces",
    "Figma Community plugins",
    "Canva Apps Marketplace",
    "Miro Marketplace",
    "FigJam widgets",
    "Adobe Express add-ons",
    "Framer Marketplace",
    "Obsidian community plugins",
    "Blender extensions",
    "design plugins, canvas widgets",
    "personal knowledge plugins",
    "game engine, AR/VR, 3D asset",
    "creator gaming marketplaces",
    "Unity Asset Store",
    "Unreal Engine Marketplace",
    "Roblox Creator Store",
    "Godot Asset Library",
    "Steamworks tools",
    "itch.io tool marketplaces",
    "Meta Quest App Lab",
    "VRChat marketplaces",
    "engine plugins, editor extensions",
    "game assets, scripts",
    "SDK integrations, creator tools",
    "avatar or world packages",
    "voice assistant, speech, meeting",
    "real-time communications app",
    "Alexa Skills Store",
    "Google Assistant Actions, Bixby",
    "Zoom App Marketplace",
    "Microsoft Teams meeting apps",
    "Slack huddle app",
    "conferencing integration catalogs",
    "voice skills, assistant actions",
    "meeting bots, call workflows",
    "transcript tools, or communications app packages",
    "messaging, SMS, chat API",
    "customer communications app marketplaces",
    "Twilio Marketplace",
    "Vonage integrations",
    "MessageBird or Bird app",
    "Sinch integrations",
    "WhatsApp Business app integrations",
    "Sendbird marketplace",
    "SMS connectors",
    "chat widgets, messaging templates",
    "contact-center workflows",
    "conversation routing apps",
    "notification automations",
    "platform-native communications packages",
    "email marketing, newsletter",
    "scheduling, event, form, and survey app",
    "Mailchimp integrations",
    "SendGrid integrations, Brevo",
    "Substack app directories",
    "Calendly integrations",
    "Eventbrite app",
    "Typeform app marketplace",
    "SurveyMonkey app directories",
    "email automations, newsletter connectors",
    "booking workflows",
    "event listings, form widgets",
    "survey templates, or platform-native integration packages",
    "maps, geospatial, travel",
    "mobility, logistics, and fleet app",
    "Google Maps Platform integrations",
    "Mapbox plugin catalog",
    "ArcGIS Marketplace",
    "QGIS plugin repository",
    "travel booking marketplaces",
    "Expedia app marketplace",
    "Uber developer app marketplaces",
    "logistics and fleet app marketplaces",
    "map plugins, GIS extensions",
    "geospatial data connectors",
    "travel booking widgets",
    "ride-hailing workflows",
    "fleet automations, or route-optimization packages",
    "code-assistant extension marketplaces",
    "developer-agent tool catalogs",
    "Amazon Q Developer, Continue, Sourcegraph Cody",
    "JetBrains Junie, Devin",
    "IDE extensions, editor plugins",
    "workspace automation packs",
    "assistant-specific tool definitions",
    "PR-editable Hermes Tweet source package entry",
    "local coding-agent command packs",
    "workflow recipes, and rule bundles",
    "GitHub Copilot Extensions, OpenCode commands",
    "Aider workflows, Goose",
    "Kiro hooks, or Amp tools",
    "agent-local prompts",
    "commands, recipes, hooks, or editor workflows",
    "source-linked Hermes Tweet package entry",
    "hosted automation, app-action, and component galleries",
    "Zapier, Pipedream, Activepieces, Composio, Arcade, Toolhouse, or Langflow",
    "workflow templates, provider connectors, hosted app actions",
    "PR-editable third-party source repository entry",
    "RPA and no-code automation marketplaces",
    "UiPath, Robocorp, n8n",
    "Make, or Workato",
    "bots, community nodes, workflow exports",
    "automation recipes, or task templates",
    "embedded `.agents`, `.agent`, `.antigravity`",
    "project-template",
    "copied skill directories inside application repositories",
    "downstream copies or mirrors",
    "fresh Hermes Tweet submission routes",
    "personal agent memory repositories",
    "OpenHands microagent folders",
    "hosted MCP directory profile pages",
    "`.openhands`, Smithery, Glama, or PulseMCP",
    "licensed, PR-editable source entry",
    "contribution rules require measurable community usage",
    "minimum star count",
    "maintainer-curated quality bar",
    "target's stated threshold",
    "closed prior Hermes Tweet PR",
    "target-specific blocker",
    "resubmit with the same evidence",
    "write Markdown bodies through a reviewed file",
    "non-interpolating path",
    "repository names, backticked literals, and validation commands",
    "`source.github` or similar repository-pointer schema",
    "canonical hub for the owner's own skills",
    "prototype marketplace applications",
    "README documents only API calls",
    "`curl` publish example is not a PR-native submission route",
    "company engineering hubs",
    "internal workflow marketplaces",
    "single-namespace catalogs",
    "Open standards, Agent Skills compatibility",
    "`third-party`, `vendor`, `upstream`, or `external` directory name",
    "branded as one owner's official catalog",
    "explicitly accept unrelated external source repositories",
    "distro installers, runtime stacks, or bundle repos",
    "external plugin reference list",
    "vendor Hermes Tweet code into another installer",
    "runtime bridges or installer extensions",
    "only help another agent consume Claude plugin marketplaces",
    "compatibility surfaces",
    "editable catalog entry for third-party plugins or source repositories",
    "translated or mirrored awesome lists",
    "translation issue tracker",
    "independent localized submission",
    "accepted adjacent entries as saturation",
    "a live Xquik, TweetClaw, OpenClaw, SocialClaw, or x-twitter-scraper entry",
    "same catalog, tool list, or awesome-list section",
    "distinct Hermes Agent plugin lane",
    "closed prior Hermes Tweet issue",
    "completed or rejected submission route",
    "unless a maintainer asks for a new PR",
    "public GitHub code search for live `Hermes Tweet`, `hermes-tweet`",
    "accepted default-branch listing",
    "record it in `docs/ECOSYSTEM.md`",
    "opening a duplicate submission",
    "local `<plugin>/.claude-plugin/plugin.json` inside the target repository",
    "external source-repository entry for third-party plugins",
    "copy, vendor, or repackage Hermes Tweet",
    "local target plugin folder",
    "official-directory snapshot lists",
    "plugins already published in an upstream official catalog",
    "status mirrors",
    "already listed in that upstream catalog",
    "Before waiting on checks, reread the outbound title, summary, and added lines",
    "close it immediately with a short scope comment",
    "off-scope outreach open",
)


def test_submission_readiness_rejects_adjacent_marketplace_routes() -> None:
    normalized_checklist = " ".join((ROOT / "docs" / "SUBMISSION_READINESS.md").read_text().split())

    for phrase in ROUTE_REJECTION_PHRASES:
        assert phrase in normalized_checklist
